
import React from 'react';
import { AlertTriangle, Shield } from 'lucide-react';

const Disclaimer = () => {
  return (
    <section id="disclaimer" className="py-20 relative">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <div className="inline-flex items-center px-4 py-2 rounded-full bg-cyber-pink/20 border border-cyber-pink/30 text-sm text-cyber-pink mb-4">
            <Shield className="h-4 w-4 mr-2" /> Legal Information
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            <span className="cyber-text text-shadow">Legal</span> Disclaimer
          </h2>
          <div className="inline-flex items-center px-4 py-2 rounded-full bg-cyber-blue/20 border border-cyber-blue/30 text-sm text-cyber-blue mb-4">
            For informational, educational, and research purposes only
          </div>
        </div>

        <div className="glass rounded-xl p-8 backdrop-blur-lg max-w-4xl mx-auto border border-white/5">
          <div className="flex items-start mb-6">
            <AlertTriangle className="h-6 w-6 text-cyber-yellow mr-3 flex-shrink-0 mt-1" />
            <p className="text-white text-lg font-medium">
              Please read this disclaimer carefully before using Data Analysis & Report AI.
            </p>
          </div>

          <div className="space-y-6 text-gray-300">
            <div>
              <h3 className="text-white font-semibold mb-2">1. No Guarantee of Accuracy</h3>
              <p>
                While Data Analysis & Report AI strives for accuracy, we make no warranties or guarantees regarding the completeness, reliability, or accuracy of any analysis, report, recommendation, or other output generated by our AI system. Results should be verified independently. Answers may be wrong sometimes.
              </p>
            </div>

            <div>
              <h3 className="text-white font-semibold mb-2">2. Not Professional Advice</h3>
              <p>
                The information provided by Data Analysis & Report AI is for general informational and research purposes only and is not intended as professional advice. It is not a substitute for professional judgment or consultations with qualified professionals in fields such as finance, healthcare, legal, or other specialized domains.
              </p>
            </div>

            <div>
              <h3 className="text-white font-semibold mb-2">3. Limitation of Liability</h3>
              <p>
                AI WEB TOOLS LLC and its affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with the use or inability to use Data Analysis & Report AI, or for any decisions made or actions taken in reliance upon the information provided.
              </p>
            </div>

            <div>
              <h3 className="text-white font-semibold mb-2">4. Data Privacy</h3>
              <p>
                By using Data Analysis & Report AI, you acknowledge that your data may be processed according to OpenAI's privacy policy. We recommend not uploading highly sensitive or confidential information unless you are comfortable with the privacy implications.
              </p>
            </div>

            <div>
              <h3 className="text-white font-semibold mb-2">5. Third-Party Content</h3>
              <p>
                When Data Analysis & Report AI conducts web searches or references external sources, we do not endorse, verify, or take responsibility for the accuracy or reliability of such third-party content.
              </p>
            </div>

            <div>
              <h3 className="text-white font-semibold mb-2">6. Usage Responsibility</h3>
              <p>
                Users are solely responsible for how they use the outputs and information provided by Data Analysis & Report AI. By using this tool, you agree to use it in a lawful manner and in compliance with all applicable laws and regulations.
              </p>
            </div>

            <div>
              <h3 className="text-white font-semibold mb-2">7. Compatibility Limitations</h3>
              <p>
                Data Analysis & Report AI may not be compatible with all file types. Users should verify compatibility before uploading or analyzing data to ensure optimal performance and accuracy of results.
              </p>
            </div>

            <p className="text-sm border-t border-white/10 pt-4 mt-4">
              By using Data Analysis & Report AI, you acknowledge that you have read, understood, and agree to this disclaimer. AI WEB TOOLS LLC reserves the right to modify this disclaimer at any time without notice.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
